version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: clave123
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app-qa:
    build: .
    environment:
      NODE_ENV: qa
      DB_HOST: db
      DB_PASSWORD: clave123
      DB_NAME: postgres
    ports:
      - "3001:3000"
    depends_on:
      - db
  app-prod:
    build: .
    environment:
      NODE_ENV: prod
      DB_HOST: db
      DB_PASSWORD: clave123
      DB_NAME: postgres
    ports:
      - "3002:3000"
    depends_on:
      - db
volumes:
  db_data: