trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'tp5-azure-connection'      # <- cambia por tu Service Connection
  resourceGroup: 'tp5-ingsoft3-2025'
  backendAppQA: 'tp5-backend-qa-soficontrerass'
  backendAppPROD: 'tp5-backend-prod-soficontrerass'
  frontendAppQA: 'tp5-frontend-qa-soficontrerass'
  frontendAppPROD: 'tp5-frontend-prod-soficontrerass'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: BuildBackend
    displayName: Build Backend
    steps:
    - checkout: self
    - script: |
        echo "Listing repo root:"
        ls -la
        echo "Listing TP5 folder:"
        ls -la TP5 || true
      displayName: 'Repo diagnostics'
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Use Node 18'
    - script: |
        if [ -d "TP5/backend" ]; then
          cd TP5/backend
          echo "Working in $(pwd)"
          npm ci || npm install
        else
          echo "ERROR: TP5/backend not found"
          exit 1
        fi
      displayName: 'Install Backend dependencies'
      failOnStderr: false
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'TP5/backend'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/backend.zip'
        replaceExistingArchive: true
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/backend.zip'
        artifact: 'backend-dist'

- job: BuildFrontend
  displayName: Build Frontend
  steps:
  - checkout: self
  - script: |
      echo "Listing TP5/frontend:"
      ls -la TP5/frontend || true
    displayName: 'Repo diagnostics'
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Use Node 18'
  - script: |
      cd TP5/frontend
      # asegurarse de que devDependencies se instalen
      export NODE_ENV=development
      npm ci --include=dev || npm install --include=dev || npm install
      npm run build
    displayName: 'Install & build Frontend'
    failOnStderr: false
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'TP5/frontend/build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'
      replaceExistingArchive: true
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/frontend.zip'
      artifact: 'frontend-dist'

- stage: Deploy_QA
  displayName: Deploy to QA
  dependsOn: Build
  jobs:
  - deployment: DeployBackendQA
    environment: 'QA'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: backend-dist
          - task: AzureWebApp@1
            displayName: 'Deploy backend to QA (Linux)'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webAppLinux'
              appName: '$(backendAppQA)'
              package: '$(Pipeline.Workspace)/backend-dist/backend.zip'

  - deployment: DeployFrontendQA
    environment: 'QA'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: frontend-dist
          - task: AzureWebApp@1
            displayName: 'Deploy frontend to QA (Linux)'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webAppLinux'
              appName: '$(frontendAppQA)'
              package: '$(Pipeline.Workspace)/frontend-dist/frontend.zip'

- stage: Deploy_PROD
  displayName: Deploy to PROD
  dependsOn: Deploy_QA
  condition: succeeded()
  jobs:
  - deployment: DeployBackendPROD
    environment: 'PROD'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: backend-dist
          - task: AzureWebApp@1
            displayName: 'Deploy backend to PROD (Linux)'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webAppLinux'
              appName: '$(backendAppPROD)'
              package: '$(Pipeline.Workspace)/backend-dist/backend.zip'

  - deployment: DeployFrontendPROD
    environment: 'PROD'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: frontend-dist
          - task: AzureWebApp@1
            displayName: 'Deploy frontend to PROD (Linux)'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webAppLinux'
              appName: '$(frontendAppPROD)'
              package: '$(Pipeline.Workspace)/frontend-dist/frontend.zip'