name: TP4 CI

on:
  push:
    branches: [main]
    paths:
      - 'TP4/**'
  pull_request:
    branches: [main]
    paths:
      - 'TP4/**'

jobs:
  build-front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TP4/front
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build Frontend
        run: npm run build
      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: front-dist
          path: TP4/front/build

  build-back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: TP4/back
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Test Backend
        run: npm test
      - name: Upload Backend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: back-dist
          path: TP4/back/